defaultPortal: 'DEV'
portals:
  - name: 'DEV'
    portalId: 6223912
    authType: oauth2
    auth:
      clientId: 8e9bac50-3ace-4c7d-bcfe-79e6e9954ca5
      clientSecret: 9dfd14dd-d613-4f1f-b93f-614e76b44519
      scopes:
        - content
      tokenInfo:
        expiresAt: '2019-08-02T11:56:48.454Z'
        refreshToken: a2aa1aed-8041-444c-b787-47c3c2e21c66
        accessToken: >-
          CLvei5TFLRICAgEYqPD7AiDdg7sDKOuZDDIZALv9fyHADopWceiaebF2DQ9fJMlfV1S-tzoQADEAQf8HAAAAAIAAAGB4z0IZALv9fyH-8CzeHRAlzUPR6oxSSxYXZzoTAg
