defaultPortal: DEV
portals:
  - name: DEV
    portalId: 6223912
    authType: oauth2
    auth:
      clientId: 8e9bac50-3ace-4c7d-bcfe-79e6e9954ca5
      clientSecret: 9dfd14dd-d613-4f1f-b93f-614e76b44519
      scopes:
        - content
      tokenInfo:
        expiresAt: '2019-08-02T17:27:45.673Z'
        refreshToken: a2aa1aed-8041-444c-b787-47c3c2e21c66
        accessToken: >-
          CIfdx53FLRICAgEYqPD7AiDdg7sDKOuZDDIZACCEVZ9QuedFZshL70jRaTeMt5543i_8qzoQADEAQf8HAAAAAIAAAGB4z0IZACCEVZ9jN7692Hi6YMN5Yvlknsrv844lMA
